# -----------------------------
#       M O N E T A I R E
# -----------------------------
# Made by ikeepcalm for UAPROJECT
# -----------------------------

# Things related to Economy Data Storage
# For now only DataBase (MariaDB)
eco_db_url:
eco_db_user:
eco_db_password:

# Things related to Reverence Data Storage
# For now only DataBase (MariaDB)
rep_db_url:
rep_db_user:
rep_db_password:

# Prices for the Phantom Shop items
# Different values, in range of int max and min values
building_block: 5
decoration_block: 5
tree_sapling: 1
slab: 2
wall: 2
carpet: 2
log: 15
sponge: 10
flower: 5
bookshelf: 5
beacon: 8
light: 15
shulker: 10
fan: 5
head: 14
nether_star: 14
firework: 10
template: 8
elytra: 32
music_disc: 8

# Quantity for each type of item
# Different values, in range of 1-64
q_building_block: 64
q_decoration_block: 32
q_tree_sapling: 16
q_ore_block: 4
q_slab: 64
q_wall: 64
q_carpet: 64
q_log: 64
q_sponge: 16
q_flower: 16
q_bookshelf: 16
q_beacon: 1
q_light: 4
q_shulker: 2
q_fan: 6
q_head: 1
q_nether_star: 1
q_firework: 64
q_template: x2
q_elytra: 1
q_music_disc: x1